package enumerations;

public enum MicroprocessorBrand {
    INTEL,
    AMD,
    APPLE,
    OTHER
    //QUALCOMM, SAMSUNG, MEDIATEK, HUAWEI, ROCKCHIP, ALLWINNER, NVIDIA, VIA, IBM, MOTOROLA, ZILOG, MOS, MOS_TECHNOLOGY, RCA, TOSHIBA, NEC, FUJITSU, HITACHI, SHARP, OKI, RICOH, PANASONIC, SANYO, OTHER
}
